### ISSUE TITLE
Incorrect results due to error in evaluation.py

### ISSUE THREAD

**Issue by rohit21122012** [TUT-ARG/DCASE2016-baseline-system-python#1]
Line no 101 in [DCASE2016-baseline-system-python/src/evaluation.py ](https://github.com/TUT-ARG/DCASE2016-baseline-system-python/blob/master/src/evaluation.py) is wrong, leading to incorrect evaluation results :
**Incorrect Version :**
`accuracies_per_class = self.accuracies(y_true=system_output, y_pred=annotated_ground_truth, labels=self.class_list)`
**With correction :**
`accuracies_per_class = self.accuracies(y_true=annotated_ground_truth, y_pred=system_output, labels=self.class_list)`

**Comment by toni-heittola** [comment]
Error corrected, and baseline performance number updated (75% => 72%) to the readme-files.
