### ISSUE TITLE
About the computation of the mfcc features

### ISSUE THREAD

**Issue by BigeyeDestroyer** [TUT-ARG/DCASE2016-baseline-system-python#5]
Maybe there is a little error in the file /src/features.py when you get the 'window' vector for mfcc feature computation: window = scipy.signal.hamming(mfcc_params['n_fft'], sym=False). But I think we should use mfcc_params['win_length'] when get the hamming window.

**Comment by toni-heittola** [comment]
librosa.stft requires window function to same length than n_fft. In case of mismatch between window length and n_fft parameter, an error is raised.

**Comment by BigeyeDestroyer** [comment]
Thank you professor, I got it ~
