### ISSUE TITLE
Audio read code without attribution in src/files.py

### ISSUE THREAD

**Issue by arryon** [TUT-ARG/DCASE2016-baseline-system-python#6]
The snippet to read a 24 bit PCM wav file in src/files.py , [starting at L63](https://github.com/TUT-ARG/DCASE2016-baseline-system-python/blob/master/src/files.py#L63), is directly copied from the 'wavio' repository. You can view the original here: https://github.com/WarrenWeckesser/wavio/blob/master/wavio.py.

I think an edit of the code with proper license attribution is warranted.

**Comment by toni-heittola** [comment]
Sorry for late reply on this. The attribution is indeed warranted, for some reason this was left out. This was not my intention. The audio reading code was changed to use pysoundfile package in commit 73fecfcc884f98a628cc37a65e18af382977e8fd.
